services:
  - type: web
    name: risbow-backend
    env: node
    plan: free
    region: oregon
    branch: master
    autoDeploy: true
    buildCommand: npm ci && npm run build
    preDeployCommand: npx prisma migrate deploy
    startCommand: npm run start:prod
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.rxticediycnboewmsfmi:EVMivjrwhqN1somD@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1"
      - key: DIRECT_URL
        value: "postgresql://postgres.rxticediycnboewmsfmi:EVMivjrwhqN1somD@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres"
      - key: JWT_SECRET
        value: "set-in-dashboard"
      - key: JWT_EXPIRY
        value: "7d"
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: "production"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: APP_BASE_URL
        value: "https://risbow-backend.onrender.com"
      - key: LOG_LEVEL
        value: "info"
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: NODE_VERSION
        value: "20"
      - key: RAZORPAY_KEY_ID
        value: "set-in-dashboard"
      - key: RAZORPAY_KEY_SECRET
        value: "set-in-dashboard"
      - key: THROTTLE_TTL
        value: "60000"
      - key: THROTTLE_LIMIT
        value: "100"

