services:
  - type: web
    name: risbow-backend
    env: node
    plan: free
    region: oregon
    branch: master
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.rxticediycnboewmsfmi:EVMivjrwhqN1somD@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres"
      - key: JWT_SECRET
        value: "set-in-dashboard"
      - key: PORT
        sync: false
      - key: REDIS_HOST
        value: "set-in-dashboard"
      - key: REDIS_PORT
        value: "6379"
      - key: NODE_VERSION
        value: "20"
      - key: RAZORPAY_KEY_ID
        value: "set-in-dashboard"
      - key: RAZORPAY_KEY_SECRET
        value: "set-in-dashboard"
      - key: THROTTLE_TTL
        value: "60000"
      - key: THROTTLE_LIMIT
        value: "100"

